#! /bin/sh

bspc config border_width		2
bspc config window_gap			16

bspc config top_padding			40
bspc config bottom_padding		10
bspc config left_padding		10
bspc config right_padding		10

bspc config split_ratio			0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config focus_follows_pointer	false
bspc config focus_follows_monitor	false

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Firefox desktop=^1
bspc rule -a luakit desktop=^1
bspc rule -a steam desktop=^4 follow=no
bspc rule -a Steam desktop=^4 follow=no

