#! /bin/sh

bspc config border_width		2
bspc config window_gap			12

bspc config top_padding			38
bspc config bottom_padding		6
bspc config left_padding		6
bspc config right_padding		6

bspc config split_ratio			0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config focus_follows_pointer	true
bspc config focus_follows_monitor	false

bspc config focused_border_color '#70b0d0'
bspc config active_border_color '#70b0d0'

bspc config remove_disabled_monitor true
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor LVDS1 -d I II III IV V
bspc monitor VGA1 -d VI VII VIII IX X
#bspc monitor DP-1 -d VIII IX X

bspc rule -a Firefox desktop=^1
bspc rule -a luakit desktop=^1
bspc rule -a Google-chrome-stable desktop=^1
bspc rule -a steam desktop=^5 follow=no
bspc rule -a Steam desktop=^5 follow=no

