hosts: localhost
  become: true
  tasks:
  - name: Add the flathub flatpak repository
    flatpak_remote:
      name: flathub
      state: present
      method: user
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install system flatpaks
    flatpak:
      name: "{{ item }}"
      state: present
    with_items:
      - app.drey.Warp
      - com.bitwarden.desktop
      - com.calibre_ebook.calibre
      - com.discordapp.Discord
      - com.fightcade.Fightcade
      - com.github.marhkb.Pods
      - com.google.Chrome
      - com.mattjakeman.ExtensionManager
      - com.spotify.Client
      - com.valvesoftware.Steam
      - net.lutris.Lutris
      - org.gnome.Boxes
      - org.gnome.eog
      - org.gnome.gitlab.somas.Apostrophe
      - org.gimp.GIMP
      - org.kde.filelight
      - org.mozilla.firefox
      - org.qbittorrent.qBittorrent
      - org.remmina.Remmina
      - org.torproject.torbrowser-launcher
      - org.videolan.VLC
      - us.zoom.Zoom

  - name: Copy controller configuration udev rules
    copy:
      src: "{{ item }}"
      dest: /etc/udev/rules.d/
      owner: root
      group: root
      mode: 0644
    with_fileglob:
      - silverblue_host/udev/99-*.rules

  - name: Load uinput at boot
    copy:
      src: silverblue_host/udev/uinput.conf
      dest: /etc/modules-load.d/
      owner: root
      group: root
      mode: 0644

  - debug:
    msg: Don't forget to stow your dotfiles :)
